- block:
  - name: destroy droplet {{ droplet.name }}
    digital_ocean:
      api_token={{ token }}
      name={{ droplet.name }}
      unique_name=yes
      state=deleted
    register: deleted
  - name: remove dns for {{ droplet.name }}
    digital_ocean_domain:
      api_token={{ token }}
      name={{ droplet.name }}.{{ do_domain }}
      state=absent
  when: droplet.delete is defined
